name: Sync to CodeCommit via HTTPS

on:
  push:
    branches:
      - main  # Trigger only when main branch is pushed

jobs:
  push-to-codecommit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Set Git identity
        run: |
          git config --global user.name "LTA_Intern_Jiaqi_CLI"
          git config --global user.email "intern.jiaqi@lta.gov.sg"

      - name: Set CodeCommit remote with credentials
        run: |
          git remote add codecommit https://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/ROAD_DAMAGE_LTA
          git config --global http.https://git-codecommit.ap-southeast-1.amazonaws.com/.extraheader "AUTHORIZATION: Basic $(echo -n '${{ secrets.CODECOMMIT_USERNAME }}:${{ secrets.CODECOMMIT_PASSWORD }}' | base64)"


      - name: Push to CodeCommit
        run: |
          git push --force codecommit main
